name: DinoRiggio
favicon: null
layout_spectrum: 0.55295
typography_spectrum: 0.75511
title: 'Dino Riggio & Associates'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00529b'
    - '#ffffff'
    - '#959ca2'
    - '#5881a5'
    - '#bed9ea'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
